openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/admin/register:
    post:
      summary: 'Register Admin'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n 'status' => 'success',\n      'authorisation' => [\n         'token' => 'jwt-auth-token',\n        'type' => 'bearer'\n   ]\n}"
      tags:
        - 'Admin Authentication'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullname:
                  type: string
                  description: 'Admin Fullname.'
                  example: 'John Admin'
                email:
                  type: string
                  description: 'Admin Email.'
                  example: admin@mail.com
                password:
                  type: string
                  description: 'User Password.'
                  example: admin-secret
              required:
                - fullname
                - email
                - password
      security: []
  /api/admin/login:
    post:
      summary: 'Login Admin'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n 'status' => 'success',\n      'authorisation' => [\n         'token' => 'jwt-auth-token',\n        'type' => 'bearer'\n   ]\n}"
      tags:
        - 'Admin Authentication'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Admin Email.'
                  example: admin@mail.com
                password:
                  type: string
                  description: 'Admin Password.'
                  example: admin-secret
              required:
                - email
                - password
      security: []
  /api/user/cart/add:
    post:
      summary: 'Add Inventory To Cart'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n 'status' => \"success\",\n 'message' => \"Inventory added to cart successfully, Cart ID: 1234\"\n}"
      tags:
        - Cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                inventory_id:
                  type: integer
                  description: 'Inventory ID .'
                  example: 1234
                quantity:
                  type: integer
                  description: Quantity.
                  example: 1
              required:
                - inventory_id
                - quantity
  /api/user/cart/list:
    get:
      summary: 'List Cart Inventories'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n 'status' => \"success || error\",\n 'message' => \"success || error message\"\n 'data' => []\n}"
      tags:
        - Cart
  '/api/user/cart/delete/{cart_id}':
    delete:
      summary: 'Delete Inventory From Cart'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n 'status' => \"success || error\",\n 'message' => \"success || error message\"\n}"
      tags:
        - Cart
    parameters:
      -
        in: path
        name: cart_id
        description: 'Cart ID .'
        example: 1234
        required: true
        schema:
          type: integer
  '/api/user/cart/update/{cart_id}':
    patch:
      summary: 'Update Existing Inventory In Cart'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n 'status' => \"success || error\",\n 'message' => \"success || error message\"\n}"
      tags:
        - Cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  description: 'Quantity .'
                  example: 1234
              required:
                - quantity
      security: []
    parameters:
      -
        in: path
        name: cart_id
        description: 'Cart ID .'
        example: 1234
        required: true
        schema:
          type: integer
  /api/user/inventories:
    get:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/admin/inventory/add:
    post:
      summary: 'Create the specified resource in storage.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: rerum
                price:
                  type: number
                  description: ''
                  example: 491.0
                quantity:
                  type: number
                  description: ''
                  example: 3064531.9999
              required:
                - name
                - price
                - quantity
      security: []
  /api/admin/inventory/list:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
  '/api/admin/inventory/view/{id}':
    get:
      summary: 'Update the specified resource in storage.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the view.'
        example: in
        required: true
        schema:
          type: string
  '/api/admin/inventory/delete/{id}':
    delete:
      summary: 'Delete the specified resource in storage.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the delete.'
        example: quia
        required: true
        schema:
          type: string
  '/api/admin/inventory/update/{id}':
    patch:
      summary: 'Update the specified resource in storage.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: aut
                price:
                  type: number
                  description: ''
                  example: 0.3619
                quantity:
                  type: number
                  description: ''
                  example: 12166630.07
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the update.'
        example: dicta
        required: true
        schema:
          type: string
  /api/user/register:
    post:
      summary: 'Register User'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n 'status' => 'success',\n      'authorisation' => [\n         'token' => 'jwt-auth-token',\n        'type' => 'bearer'\n   ]\n}"
      tags:
        - 'User Authentication'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'User Full Name.'
                  example: 'John Doe'
                email:
                  type: string
                  description: 'User Email.'
                  example: admin@mail.com
                password:
                  type: string
                  description: 'User Password.'
                  example: secret
              required:
                - name
                - email
                - password
      security: []
  /api/user/login:
    post:
      summary: 'Login User'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n 'status' => 'success',\n      'authorisation' => [\n         'token' => 'jwt-auth-token',\n        'type' => 'bearer'\n   ]\n}"
      tags:
        - 'User Authentication'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'User Email.'
                  example: user@mail.com
                password:
                  type: string
                  description: 'User Password.'
                  example: secret
              required:
                - email
                - password
      security: []
tags:
  -
    name: 'Admin Authentication'
    description: ''
  -
    name: Cart
    description: ''
  -
    name: Endpoints
    description: ''
  -
    name: 'User Authentication'
    description: ''
